// packages/adaptableblotter-react/src/AdaptableBlotterAgGrid.tsx
﻿import * as React from "react";
import { AgGridReact } from 'ag-grid-react';
import { GridOptions } from "ag-grid";
import AdaptableBlotter from "./AdaptableBlotter";
import { IAdaptableBlotterOptions } from "adaptableblotter/types";

export interface AdaptableBlotterAgGridProps extends React.ClassAttributes<AdaptableBlotterAgGrid> {
  AdaptableBlotterOptions: IAdaptableBlotterOptions
  GridOptions: GridOptions
  agTheme? :'balham'|'balham-dark'|'material'| 'fresh'| 'dark'| 'blue'|'bootstrap'
  agDivStyle?: any
}

export interface AdaptableBlotterAgGridState extends React.ClassAttributes<AdaptableBlotterAgGrid> {
  AdaptableBlotterOptions: IAdaptableBlotterOptions
  GridOptions: GridOptions
}

export default class AdaptableBlotterAgGrid extends React.Component<AdaptableBlotterAgGridProps, AdaptableBlotterAgGridState> {
  componentWillMount() {
    this.state = {
      AdaptableBlotterOptions: this.props.AdaptableBlotterOptions,
      GridOptions: this.props.GridOptions
    };
  }

  render() {
    let theme: string = this.props.agTheme? "ag-theme-" + this.props.agTheme: "ag-theme-balham"
    let style : any = this.props.agDivStyle? this.props.agDivStyle: { width: '100%', height: '90%', position: 'absolute' , margin: '0px'}
    return (
      <div id="adaptableBlotter-react">
        <AdaptableBlotter AdaptableBlotterOptions={this.state.AdaptableBlotterOptions} VendorGridName="agGrid" />
        <div id="grid" className={theme} style={style} >
          <AgGridReact gridOptions={this.state.GridOptions} />
        </div>
      </div>
    )
  }
}

// packages/adaptableblotter-angular/projects/adaptableblotter/src/lib/adaptableblotter-aggrid.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { IAdaptableBlotterOptions } from 'adaptableblotter/types';
import { GridOptions } from 'ag-grid';

@Component({
  selector: 'adaptable-blotter-aggrid',
  template: `
  <div id="adaptableBlotter">
    <adaptable-blotter [adaptableBlotterOptions]="adaptableBlotterOptions" vendorGridName="agGrid">
    </adaptable-blotter>
    <div id="grid" [class]="agGridClass" [style]="agDivStyle">
      <ag-grid-angular
        [class]="agGridClass"
        [gridOptions]="gridOptions">
      </ag-grid-angular>
    </div>
  </div>`,
})
export class AdaptableblotterAgGridComponent implements OnInit {
  @Input() adaptableBlotterOptions: IAdaptableBlotterOptions;
  @Input() gridOptions: GridOptions;
  @Input() agTheme?: 'balham'|'balham-dark'|'material'| 'fresh'| 'dark'| 'blue'|'bootstrap' = 'balham';
  @Input() agDivStyle?: any = { width: '100%', height: '90%', position: 'absolute' , margin: '0px'};

  agGridClass: string;

  constructor() { }

  ngOnInit() {
    this.agGridClass = `ag-theme-${this.agTheme}`;
  }

}
