// packages/adaptableblotter-react/src/AdaptableBlotter.tsx
﻿import * as React from 'react'
import { BlotterFactory, AdaptableBlotterApp } from 'adaptableblotter/factory'
import { IAdaptableBlotter, IAdaptableBlotterOptions } from 'adaptableblotter/types'

// This is the main React Wrapper
// It simply takes an IAdaptableBlotterOptions object and instantiates the appropriate instance of the Adaptable Blotter
export interface AdaptableBlotterProps extends React.ClassAttributes<AdaptableBlotter> {
  AdaptableBlotterOptions: IAdaptableBlotterOptions
  VendorGridName: 'agGrid' | 'Hypergrid'
}

export interface AdaptableBlotterState extends React.ClassAttributes<AdaptableBlotter> {
  AdaptableBlotter: IAdaptableBlotter
}

export default class AdaptableBlotter extends React.Component<
AdaptableBlotterProps,
AdaptableBlotterState
  > {
  componentWillMount() {
    const { AdaptableBlotterOptions, VendorGridName } = this.props;
    AdaptableBlotterOptions.containerOptions.adaptableBlotterContainer =
      AdaptableBlotterOptions.containerOptions.adaptableBlotterContainer || `adaptableBlotter-${Math.random() * 10000 | 0}`;
    this.setState({
      AdaptableBlotter: BlotterFactory.CreateAdaptableBlotter(AdaptableBlotterOptions, VendorGridName)
    })
  }

  render() {
    return (
      <div id="adaptableBlotter">
        <AdaptableBlotterApp AdaptableBlotter={this.state.AdaptableBlotter} />
      </div>
    )
  }
}

// packages/adaptableblotter-angular-aggrid/projects/adaptableblotter/src/lib/adaptableblotter.component.ts
declare var require: any;

import { Component, OnInit, Input, ElementRef, Output, EventEmitter } from '@angular/core';

import { BlotterFactory, AdaptableBlotterApp } from 'adaptableblotter/factory';
import { IAdaptableBlotter, IAdaptableBlotterOptions } from 'adaptableblotter/types';
// import ReactDOM from 'react-dom';

let ReactDOM;
try {
  ReactDOM = require('react-dom');
} catch (ignored) {
  ReactDOM = require('adaptableblotter/react-dom').ReactDOM;
}

@Component({
  selector: 'adaptable-blotter',
  template: `<div [id]="adaptableBlotterOptions.containerOptions.adaptableBlotterContainer">Loading...</div>`,
  styles: []
})
export class AdaptableBlotterComponent implements OnInit {
  @Input() adaptableBlotterOptions: IAdaptableBlotterOptions;
 
  @Output() adaptableBlotterMounted = new EventEmitter<any>();

  private adaptableBlotter: IAdaptableBlotter;

  constructor(private elRef: ElementRef) { }

  ngOnInit() {
    this.adaptableBlotterOptions.containerOptions.adaptableBlotterContainer =
      this.adaptableBlotterOptions.containerOptions.adaptableBlotterContainer || `adaptableBlotter-${Math.random() * 10000 | 0}`;
    const waitForContainer = setInterval(() => {
      try {
        document.getElementById(this.adaptableBlotterOptions.containerOptions.adaptableBlotterContainer);
        // Element is mounted
        this.adaptableBlotter = BlotterFactory.CreateAdaptableBlotter(
          this.adaptableBlotterOptions,
          'agGrid'
        );
        this.adaptableBlotterMounted.emit(this.adaptableBlotter);
        ReactDOM.render(
          AdaptableBlotterApp({ AdaptableBlotter: this.adaptableBlotter }),
          this.elRef.nativeElement.firstChild,
        );
        clearInterval(waitForContainer);
      } catch (e) {
      }
    }, 100);
  }

}
