// packages/adaptableblotter-react-test/src/App.tsx
import * as React from "react";
import { GridOptions } from "ag-grid-community";
import { DataGenerator } from "./DataGenerator";
import { AdaptableBlotter, IAdaptableBlotterOptions } from "adaptableblotter-react";
import { AgGridReact } from "ag-grid-react";
import "ag-grid-community/dist/styles/ag-grid.css";
import "ag-grid-community/dist/styles/ag-theme-balham.css";
import "ag-grid-community/dist/styles/ag-theme-balham-dark.css";

import { ReactHarnessHelper } from "./ReactHarnessHelper";
import 'adaptableblotter-react/dist/styles/adaptableblotter-style.css';

export interface AppState extends React.ClassAttributes<App> {
  gridOptions: GridOptions;
  blotterOptions: IAdaptableBlotterOptions;
  rowData: any;
  columnDefs: any;
}

export default class App extends React.Component<{}, AppState> {
  constructor(props: any) {
    super(props);
    let gridOptions: GridOptions = {
      enableRangeSelection: true,
    };
    this.state = {
      gridOptions: gridOptions,
      blotterOptions: {
        primaryKey: "tradeId",
        vendorGrid: gridOptions,
        userName: "Blotter Wrapper user",
        blotterId: "Adaptable Blotter Wrapper",
        containerOptions: {
         adaptableBlotterContainer: "adaptableBlotter",
          vendorContainer: "grid",
          modalContainer: null,
          chartContainer: null,
        },
      },
      rowData: new DataGenerator().getTrades(15000),
      columnDefs: new ReactHarnessHelper().getTradeSchema()
    };
  }

  render() {
    return (
      <div>
        <AdaptableBlotter
          AdaptableBlotterOptions={this.state.blotterOptions}
          VendorGridName={"agGrid"}
        />
        <div id="grid" style={{ height: "97vh", width: "100%" }}>
          <AgGridReact
            columnDefs={this.state.columnDefs}
            rowData={this.state.rowData}
            gridOptions={this.state.gridOptions}
          />
        </div>
      </div>
    );
  }
}

// packages/adaptableblotter-angular-aggrid/src/app/app.component.ts
import { Component } from '@angular/core';
import { GridOptions } from 'ag-grid-community';
import HarnessHelper from './harness-helper';
import DataGenerator from './data-generator';
import { IAdaptableBlotterOptions } from 'adaptableblotter-angular-aggrid';

@Component({
  selector: 'adaptableblotter-root',
  template: `
    <div>
      <adaptable-blotter [adaptableBlotterOptions]="blotterOptions"> </adaptable-blotter>
      <div id="grid">
        <ag-grid-angular
          style="width: 100%; height: 97vh;"
          class="ag-theme-balham"
          [rowData]="rowData"
          [columnDefs]="columnDefs"
          [gridOptions]="gridOptions"
        >
        </ag-grid-angular>
      </div>
    </div>
  `,
})
export class AppComponent {
  gridOptions: GridOptions = {
    columnDefs: new HarnessHelper().getTradeSchema(),
    rowData: new DataGenerator().getTrades(5000),
    enableRangeSelection: true,
  };

  blotterOptions: IAdaptableBlotterOptions = {
    primaryKey: 'tradeId',
    vendorGrid: this.gridOptions,
    userName: 'demo user',
    blotterId: 'angular wrapper',
    licenceKey: 'Community',
    containerOptions: {
      adaptableBlotterContainer: 'adaptableBlotter',
    },
  };
}
