// packages/adaptableblotter-react-test/src/App.tsx
import * as React from 'react';
import { GridOptions } from "ag-grid";
import { AdaptableBlotter, IAdaptableBlotterOptions } from 'adaptableblotter-react';
import { AgGridReact } from 'ag-grid-react';
//import 'ag-grid/dist/styles/ag-grid.css';
//import 'ag-grid/dist/styles/ag-theme-balham.css';

export interface AppState extends React.ClassAttributes<App> {
  gridOptions: GridOptions,
  blotterOptions: IAdaptableBlotterOptions,
  rowData: any,
  columnDefs: any
}

export default class App extends React.Component<{}, AppState> {
  constructor(props: any) {
    super(props);
    let gridOptions: GridOptions = {
      enableSorting: true
    }
    this.state = {
      gridOptions: gridOptions,
      blotterOptions: {
        primaryKey: "make",
        vendorGrid: gridOptions,
        userName: 'UtibeAbasi',
        blotterId: "demo blotter",
      },
      rowData: [
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 }
      ],
      columnDefs: [
        { headerName: "Make", field: "make" },
        { headerName: "Model", field: "model" },
        { headerName: "Price", field: "price" }
      ],
    }
  }

  render() {
    return (
      <div>
        <AdaptableBlotter AdaptableBlotterOptions={this.state.blotterOptions} VendorGridName={"agGrid"} />
        <div className='ag-theme-balham' style={{ height: '97vh', width: '100%' }}>
          <AgGridReact
            columnDefs={this.state.columnDefs}
            rowData={this.state.rowData}
            gridOptions={this.state.gridOptions} />
        </div>
      </div>
    );
  }
}

// packages/adaptableblotter-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { IAdaptableBlotterOptions } from 'adaptableblotter-angular';
import { GridOptions } from 'ag-grid';

@Component({
  selector: 'adaptableblotter-root',
  template: `
  <div>
    <adaptable-blotter
      [adaptableBlotterOptions]="blotterOptions"
      vendorGridName="agGrid">
    </adaptable-blotter>
    <ag-grid-angular
      style="width: 100%; height: 97vh;"
      class="ag-theme-balham"
      [rowData]="rowData"
      [columnDefs]="columnDefs"
      [gridOptions]="gridOptions">
    </ag-grid-angular>
  </div>
  `
})
export class AppComponent {
  rowData = [
    { make: 'Toyota', model: 'Celica', price: 35000 },
    { make: 'Ford', model: 'Mondeo', price: 32000 },
    { make: 'Porsche', model: 'Boxter', price: 72000 }
  ];

  columnDefs = [
    { headerName: 'Make', field: 'make' },
    { headerName: 'Model', field: 'model' },
    { headerName: 'Price', field: 'price' }
  ];

  gridOptions: GridOptions = {
    enableSorting: true,
    enableRangeSelection: true,
    enableFilter: true,
    enableColResize: true
  };

  blotterOptions: IAdaptableBlotterOptions = {
    primaryKey: 'make',
    vendorGrid: this.gridOptions,
    userName: 'demo user',
    blotterId: 'demo blotter',
  };
}
